### obteniendo todos los eventos
GET http://localhost:3000/eventos

### obteniendo un evento
GET http://localhost:3000/eventos/1

### creando un evento
POST http://localhost:3000/eventos

### editando un evento
PUT http://localhost:3000/eventos/1

### eliminando un evento
DELETE http://localhost:3000/eventos/7


### obteniendo todos los usuario
GET http://localhost:3000/usuarios

### obteniendo un usuario
GET http://localhost:3000/usuarios/1

### creando un usuario
POST http://localhost:3000/usuarios

### editando un usuario
PUT http://localhost:3000/usuarios/1

### eliminando un usuario
DELETE http://localhost:3000/usuarios/7


### obteniendo todos los ticket
GET http://localhost:3000/tickets

### obteniendo un ticket
GET http://localhost:3000/tickets/1

### creando un ticket
POST http://localhost:3000/tickets

### editando un ticket
PUT http://localhost:3000/tickets/1

### eliminando un ticket
DELETE http://localhost:3000/tickets/7


### obteniendo todos los review
GET http://localhost:3000/reviews

### obteniendo un revieww
GET http://localhost:3000/reviews/1

### creando un revieww
POST http://localhost:3000/reviews

### editando un revieww
PUT http://localhost:3000/reviews/1

### eliminando un revieww
DELETE http://localhost:3000/reviews/7


### obteniendo todos los order
GET http://localhost:3000/orders

### obteniendo un orderw
GET http://localhost:3000/orders/1

### creando un orderw
POST http://localhost:3000/orders

### editando un orderw
PUT http://localhost:3000/orders/1

### eliminando un orderw
DELETE http://localhost:3000/orders/7


### obteniendo todos los favoritos
GET http://localhost:3000/favoritos

### obteniendo un favorito
GET http://localhost:3000/favoritos/1

### creando un favorito
POST http://localhost:3000/favoritos

### editando un favorito
PUT http://localhost:3000/favoritos/1

### eliminando un favorito
DELETE http://localhost:3000/favoritos/7


### obteniendo todos los cupones
GET http://localhost:3000/cupones

### obteniendo un cupone
GET http://localhost:3000/cupones/1

### creando un cupone
POST http://localhost:3000/cupones

### editando un cupone
PUT http://localhost:3000/cupones/1

### eliminando un cupone
DELETE http://localhost:3000/cupones/7


### obteniendo todos los notificaciones
GET http://localhost:3000/notificaciones

### obteniendo una notificacion
GET http://localhost:3000/notificaciones/1

### creando una notificacion
POST http://localhost:3000/notificaciones

### editando una notificacion
PUT http://localhost:3000/notificaciones/1

### eliminando una notificacion
DELETE http://localhost:3000/notificaciones/7